// frontend/src/App.tsx
import { useHttpClient } from "@context/HttpClientContext";
import TodoList from "./entity/TodoList";
import { useEffect, useState } from "react";

export const App = () => {
  const { todosGateway } = useHttpClient();
  const [total, setTotal] = useState(0)
  const [completed, setCompleted] = useState(0)
  const [description, setDescription] = useState('')

  let todoList: TodoList;
  useEffect(() => {
    const fetchData = async () => {
      todoList = new TodoList()
      const todosData = await todosGateway.getTodos();
      todoList.addTodos(todosData);
      setTotal(todoList.getTotal())
      setCompleted(todoList.getCompleted())
    }

    fetchData()
  }, [])

  return (
    <div>
      <h2>Total: {total}</h2>
	    <h2>Completed: {completed}%</h2>


      <input role="input" type="text" onChange={e => setDescription(e.target.value)}  />
      <button className="add-todo-button" onClick={() => todoList.addTodo(description)}>Add</button>
    </div>
  );
};

// frontend/src/App.vue
<script setup lang="ts">
  import { inject, onMounted, reactive } from 'vue'
  import TodosGateway from './infra/gateway/TodosGateway';
  import TodoList from './entity/TodoList';

  const todoList: any = reactive(new TodoList());
  const description = ""

  onMounted(async () => {
    const todosGateway = inject('todosGateway') as TodosGateway
    const todosData = await todosGateway.getTodos()
    todoList.addTodos(todosData)
  })
</script>

<template>
    <div class="total">Total: {{ todoList.getTotal() }}</div>
    <div class="completed">Completed: {{ todoList.getCompleted() }}%</div>
    <div v-for="todo in todoList.todos">
      <div class="todo-description" type="text">{{ todo.description }}</div>
      <div class="todo-done" type="text">{{ todo.done }}</div>
      <button class="todo-toggle-done-button" @click="todo.toggleDone()">done/undone</button>
      <button class="todo-delete-button" @click="todoList.deleteTodo(todo)">delete</button>
    </div>
    <input class="todo-description-input" type="text" v-model="description" />
    <button class="add-todo-button" @click="todoList.addTodo(description)" type="submit">Add</button>
</template>

<style scoped>
</style>
